# Generated by Django 2.0.2 on 2018-10-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time', models.DateField()),
                ('revision', models.IntegerField()),
                ('book_isbn', models.CharField(max_length=64)),
                ('word_count', models.CharField(max_length=64)),
                ('page_count', models.IntegerField()),
                ('open_type', models.CharField(max_length=20)),
                ('book_paper', models.CharField(max_length=64)),
                ('book_wrapper', models.CharField(max_length=64)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_dprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('editor_recommendation', models.IntegerField()),
                ('content_introduction', models.CharField(max_length=2000)),
                ('author_introduction', models.CharField(max_length=2000)),
                ('menu', models.CharField(max_length=2000)),
                ('media_review', models.CharField(max_length=2000)),
                ('digest_image_path', models.CharField(max_length=2000)),
                ('product_image_path', models.CharField(max_length=2000)),
                ('series_name', models.CharField(max_length=128)),
                ('printing_time', models.DateField()),
                ('impression', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
                ('shelves_date', models.DateField()),
                ('customer_socre', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book_status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('sales', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('book_counts', models.DecimalField(decimal_places=0, max_digits=10)),
                ('category_pid', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 't_catagory',
            },
        ),
        migrations.AddField(
            model_name='tbook',
            name='book_category',
            field=models.ForeignKey(db_column='book_category', on_delete=django.db.models.deletion.DO_NOTHING, to='books.TCatagory'),
        ),
    ]
