# Generated by Django 2.0.2 on 2018-10-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.TUser')),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=0, max_digits=20)),
                ('create_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('order_addrid', models.ForeignKey(db_column='order_addrid', on_delete=django.db.models.deletion.DO_NOTHING, to='indent.TAddress')),
                ('order_uid', models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.TUser')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TOrderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_num', models.DecimalField(decimal_places=0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shop_bookid', models.ForeignKey(db_column='shop_bookid', on_delete=django.db.models.deletion.DO_NOTHING, to='books.TBook')),
                ('shop_ordid', models.ForeignKey(db_column='shop_ordid', on_delete=django.db.models.deletion.DO_NOTHING, to='indent.TOrder')),
            ],
            options={
                'db_table': 't_orderitem',
            },
        ),
    ]
